# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('pid', models.BigIntegerField()),
                ('sku', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('addtime', models.DateTimeField()),
            ],
            options={
                'ordering': ['-addtime'],
            },
        ),
    ]
